spring:
  profiles:
    active: dev

---
# spring 配置
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: spring-provider-dept

# Eureka 配置
# 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
# spring 配置
server:
  port: 8202
spring:
  profiles: test
  application:
    name: spring-provider-dept

# Eureka 配置
# 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/