spring:
  profiles:
    active: dev

---
server:
  port: 7001

# spring 配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
  
# Eureka 配置
eureka:
  instance:
    hostname: eureka7001.com # Eureka 服务端的示例名称
  client:
    register-with-eureka: false # 是否向 Eureka 注册中心注册自己
    fetch-registry: false # 是否从 Eureka 中获取注册信息
    service-url:  # 监控页面
      # 单机 ： http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）
     defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
     
---
server:
  port: 7001

# spring 配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
  
# Eureka 配置
eureka:
  instance:
    hostname: eureka7001.com # Eureka 服务端的示例名称
  client:
    register-with-eureka: false # 是否向 Eureka 注册中心注册自己
    fetch-registry: false # 是否从 Eureka 中获取注册信息
    service-url:  # 监控页面
      # 单机 ： http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）
     defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/